# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcaadmin', '0002_auto_20160111_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simresult',
            name='mode',
            field=models.CharField(choices=[('block', 'Sweep'), ('sweep:', 'Block'), ('alt:', 'Alt')], max_length=100),
        ),
    ]
