# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcaadmin', '0003_auto_20160117_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simresult',
            name='mode',
            field=models.CharField(choices=[('sweep', 'Sweep'), ('block:', 'Block'), ('alt:', 'Alt')], max_length=100),
        ),
    ]
